
# Docs: https://packit.dev/docs/

upstream_project_url: git@github.com:dracut-ng/dracut-ng.git

## TODO: #####################
# unify - the only difference

files_to_sync:
- src: .distro/
  dest: .
  delete: true
  filters:
  - protect .git*
  - protect sources
  - protect .fmf*
  - protect gating.yaml
  - protect plans.fmf
  - protect ci.fmf
  - exclude source-git.yaml
  - exclude .gitignore
  - exclude *.sh

#files_to_sync:
#  - .distro/dracut.spec

##############################

sources:
- path: dracut-ng-107.tar.gz
  url: https://github.com/dracut-ng/dracut-ng/archive/refs/tags/107.tar.gz

specfile_path: .distro/dracut.spec

patch_generation_ignore_paths:
- .distro/
- .packit.yml
- .github/
- .editorconfig
- test/
patch_generation_patch_id_digits: 1
sync_changelog: true

# TODO: #
#upstream_ref: "107"
upstream_ref: 279da16f1b8fcca27d41937967c4e8f4c295086a

upstream_package_name: dracut
downstream_package_name: dracut

#actions:
#  post-upstream-clone:
    # Use the current specfile
#    - "cp pkgbuild/dracut.spec ."

jobs:
# Build test
- job: upstream_koji_build
  trigger: pull_request
  scratch: true
  targets:
    - fedora-rawhide-x86_64
    - fedora-eln-x86_64

- job: copr_build
  trigger: pull_request
  targets:
    - fedora-rawhide-x86_64
    - fedora-eln-x86_64

# Run tests (via testing farm)
- job: tests
  trigger: pull_request
  targets:
    - fedora-rawhide-x86_64
#    - fedora-eln-x86_64

## Create PR
#- job: propose_downstream
#  trigger: release
#  dist_git_branches:
#    -
