# Docs: https://packit.dev/docs/

specfile_path: pkgbuild/dracut.spec

files_to_sync:
  - pkgbuild/dracut.spec

upstream_package_name: dracut
downstream_package_name: dracut

#actions:
#  post-upstream-clone:
    # Use the current specfile
#    - "cp pkgbuild/dracut.spec ."

jobs:
# Build test
- job: upstream_koji_build
  trigger: pull_request
  targets:
    - fedora-rawhide-x86_64
    - fedora-eln-x86_64

- job: copr_build
  trigger: pull_request
  targets:
    - fedora-rawhide-x86_64
    - fedora-eln-x86_64

# Run tests (via testing farm)
- job: tests
  trigger: pull_request
  targets:
    - fedora-rawhide-x86_64
    - fedora-eln-x86_64

# Create fedora PR
- job: propose_downstream
  trigger: release
  dist_git_branches:
    - rawhide
