FROM quay.io/centos/centos:stream10-development

MAINTAINER https://github.com/redhat-plumbers/dracut-rhel10

ENV container=docker
LABEL RUN="docker run -it --name NAME --privileged --ipc=host --net=host --pid=host -e NAME=NAME -e IMAGE=IMAGE IMAGE"

RUN echo 'export DRACUT_NO_XATTR=1 KVERSION=$(cd /lib/modules; ls -1 | tail -1)' > /etc/profile.d/dracut-test.sh

# Install needed packages for the dracut CI container
# FIXME: properly re-add dash once C10S EPEL is available
RUN dnf -y install --skip-broken --enablerepo crb --setopt=install_weak_deps=False \
    https://kojipkgs.fedoraproject.org//packages/dash/0.5.12/4.eln141/x86_64/dash-0.5.12-4.eln141.x86_64.rpm \
    qemu-kvm \
    NetworkManager \
    asciidoc \
    bash-completion \
    bzip2 \
    cryptsetup \
    dbus-daemon \
    dhcp \
    e2fsprogs \
    gcc \
    git \
    iproute \
    iputils \
    iscsi-initiator-utils \
    kbd \
    kernel \
    kmod-devel \
    lvm2 \
    make \
    mdadm \
    nfs-utils \
    parted \
    pigz \
    rpm-build \
    squashfs-tools \
    strace \
    sudo \
    tar \
    tcpdump \
    wget \
    which \
    xz
#    && dnf -y update && dnf clean all

# C10S ships only qemu-kvm, but it disables the KVM accel when it's not
# available
RUN ln -sv /usr/libexec/qemu-kvm /usr/bin/qemu-kvm && \
    ln -sv /usr/libexec/qemu-kvm /usr/bin/qemu-system-$(uname -m)

# From Fedora container
# Install needed packages for the dracut CI container
RUN dnf -y install --skip-broken --setopt=install_weak_deps=False \
    asciidoc \
    astyle \
    bash-completion \
    bluez \
    btrfs-progs \
    busybox \
    bzip2 \
    cargo \
    cifs-utils \
    cryptsetup \
    dash \
    dbus-daemon \
    device-mapper-multipath \
    dhcp-client \
    dhcp-server \
    dmraid \
    e2fsprogs \
    erofs-utils \
    f2fs-tools \
    fcoe-utils \
    fuse3 \
    gcc \
    git \
    iproute \
    iputils \
    iscsi-initiator-utils \
    jq \
    kbd \
    kernel \
    kmod-devel \
    libkcapi-hmaccalc \
    libselinux-utils \
    lvm2 \
    lzop \
    make \
    mdadm \
    memstrack \
    mksh \
    nbd \
    ndctl \
    NetworkManager \
    nfs-utils \
    ntfs-3g \
    ntfsprogs \
    nvme-cli \
    parted \
    pcsc-lite \
    pigz \
    qemu \
    qrencode \
    rng-tools \
    rpm-build \
    sbsigntools \
    scsi-target-utils \
    ShellCheck \
    shfmt \
    squashfs-tools \
    strace \
    systemd-boot-unsigned \
    systemd-networkd \
    systemd-resolved \
    systemd-ukify \
    tar \
    tcpdump \
    tpm2-tools \
    wget \
    xz \
    && dnf -y remove dracut --noautoremove && dnf -y update && dnf clean all
