---
name: Daily Integration Tests

on:  # yamllint disable-line rule:truthy
    schedule:
        - cron: '30 23 * * *'   # every day at 23:30 UTC

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

    pull_request:
        paths:
            - '.github/workflows/integration-extra.yml'

jobs:
    basic:
        # run this test on all containers
        name: ${{ matrix.test }} on ${{ matrix.container }}
        runs-on: ubuntu-24.04
        timeout-minutes: 20
        concurrency:
            group: extra-basic-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}
            cancel-in-progress: true
        strategy:
            fail-fast: false
            matrix:
                container:
                    - fedora:latest
                    - fedora:rawhide
                    - centos:stream10-development
                test:
                    - "10"
                    - "11"
                    - "12"
                    - "13"
                    - "20"
                    - "26"
                    - "30"
                    - "40"
                    - "41"
                    - "42"
                    - "43"
                    - "50"
                    - "80"
                    - "81"
                    - "82"
                exclude:
                    # https://github.com/dracut-ng/dracut-ng/issues/1224
                    - container: gentoo:amd64-openrc
                      test: "43"
                    # https://github.com/dracut-ng/dracut-ng/issues/1407
                    - container: debian:sid
                      test: "12"
                    # https://github.com/dracut-ng/dracut-ng/issues/1590
                    - container: ubuntu:rolling
                      test: "30"
                    # https://github.com/dracut-ng/dracut-ng/issues/1677
                    - container: arch:latest
                      test: "41"
        container:
            image: ghcr.io/${{ github.repository_owner }}/${{ matrix.container }}-amd
            options: '--device=/dev/kvm --privileged'
        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v5
            - name: "${{ matrix.container }} TEST-${{ matrix.test }}"
              run: ./test/test-container.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
    network-systemd:
        name: ${{ matrix.test }} on ${{ matrix.container }} ${{ matrix.network }} networking
        runs-on: ubuntu-24.04
        timeout-minutes: 20
        concurrency:
            group: extra-network-systemd-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}-${{ matrix.network }}
            cancel-in-progress: true
        strategy:
            fail-fast: false
            matrix:
                network:
                    - systemd-networkd
                container:
                    - fedora:latest
                test:
                    - "50"
        container:
            image: ghcr.io/${{ github.repository_owner }}/${{ matrix.container }}-amd
            options: '--device=/dev/kvm'
        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v5
            - name: "${{ matrix.container }} TEST-${{ matrix.test }}"
              run: USE_NETWORK=${{ matrix.network }} ./test/test-container.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
    network-manager:
        name: ${{ matrix.test }} on ${{ matrix.container }} ${{ matrix.network }} networking
        runs-on: ubuntu-24.04
        timeout-minutes: 20
        concurrency:
            group: extra-network-manager-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}-${{ matrix.network }}
            cancel-in-progress: true
        strategy:
            fail-fast: false
            matrix:
                network:
                    - network-manager
                container:
                    - fedora:latest
                    - fedora:rawhide
                test:
                    - "60"
                    - "70"
                    - "71"
                    - "72"
        container:
            image: ghcr.io/${{ github.repository_owner }}/${{ matrix.container }}-amd
            options: '--device=/dev/kvm'
        steps:
            - name: "Checkout Repository"
              uses: actions/checkout@v5
            - name: "${{ matrix.container }} TEST-${{ matrix.test }}"
              run: USE_NETWORK=${{ matrix.network }} ./test/test-container.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
