name: Integration Test

on:
    pull_request:
        branches: [ main ]

env:
    DEBUGFAIL: "${{ secrets.ACTIONS_STEP_DEBUG && 'rd.debug' }}"

jobs:
    basic:
        name: ${{ matrix.test }} on ${{ matrix.container }}
        runs-on: ubuntu-latest
        timeout-minutes: 45
        concurrency:
            group: basic-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}
            cancel-in-progress: true
        strategy:
            matrix:
                container: [
                        "fedora",
                ]
                test: [
                        "01",
                ]
            fail-fast: false
        container:
            image: ghcr.io/dracut-ng/${{ matrix.container }}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v4
            -   name: "${{ matrix.container }} TEST-${{ matrix.test }}"
                run: ./tools/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
    network:
        name: ${{ matrix.test }} on ${{ matrix.container }} using ${{ matrix.network }}
        runs-on: ubuntu-latest
        timeout-minutes: 45
        concurrency:
            group: network-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}-${{ matrix.network }}
            cancel-in-progress: true
        strategy:
            matrix:
                container: [
                        "fedora",
                ]
                network: [
                        "network",
                ]
                test: [
                        "20",
                        "40",
                        "50",
                        "60",
                ]
            fail-fast: false
        container:
            image: ghcr.io/dracut-ng/${{ matrix.container }}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v4
            -   name: "${{ matrix.container }} TEST-${{ matrix.test }}"
                run: USE_NETWORK=${{ matrix.network }} ./tools/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
    systemd-networkd:
        name: ${{ matrix.test }} on ${{ matrix.container }} using ${{ matrix.network }}
        runs-on: ubuntu-latest
        timeout-minutes: 45
        concurrency:
            group: systemd-networkd-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}-${{ matrix.network }}
            cancel-in-progress: true
        strategy:
            matrix:
                container: [
                        "arch",
                ]
                network: [
                        "systemd-networkd",
                ]
                test: [
                        "35",
                        "40",
                ]
            fail-fast: false
        container:
            image: ghcr.io/dracut-ng/${{ matrix.container }}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v4
            -   name: "${{ matrix.container }} TEST-${{ matrix.test }}"
                run: USE_NETWORK=${{ matrix.network }} ./tools/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
    extended:
        name: ${{ matrix.test }} on ${{ matrix.container }}
        runs-on: ubuntu-latest
        timeout-minutes: 30
        concurrency:
            group: extended-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}
            cancel-in-progress: true
        strategy:
            matrix:
                container: [
                        "fedora",
                ]
                test: [
                        "02",
                        "03",
                        "04",
                        "10",
                        "11",
                        "12",
                        "13",
                        "14",
                        "15",
                        "16",
                        "17",
                        "18",
                        "62",
                        "98",
                ]
            fail-fast: false
        container:
            image: ghcr.io/${{ github.repository_owner }}/${{ matrix.container }}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v4
            -   name: "${{ matrix.container }} TEST-${{ matrix.test }}"
                run: ./tools/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
    dracut-cpio:
        name: ${{ matrix.test }} on ${{ matrix.container }}
        runs-on: ubuntu-latest
        timeout-minutes: 30
        concurrency:
            group: dracut-cpio-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}


            cancel-in-progress: true
        strategy:
            matrix:
                container: [
                        "fedora",
                ]
                network: [
                        "network-manager",
                        #"systemd-networkd",
                        #"connman",
                ]
                test: [
                        "20",
                        "30",
                        "35",
                        "40",
                        "50",
                        "60",
                ]
            fail-fast: false
        container:
            image: ghcr.io/${{ github.repository_owner }}/${{ matrix.container }}
            options: "--privileged -v /dev:/dev"
        steps:
            -   name: "Checkout Repository"
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0

            -   name: "${{ matrix.container }} TEST-${{ matrix.test }}"
                run: USE_NETWORK=${{ matrix.network }} ./tools/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
    arm64:
        name: ${{ matrix.test }} on ${{ matrix.container }} on arm64
        runs-on: ubuntu-latest
        timeout-minutes: 30
        concurrency:
            group: arm64-${{ github.workflow }}-${{ github.ref }}-${{ matrix.container }}-${{ matrix.test }}
            cancel-in-progress: true
        strategy:
            matrix:
                container: [
                        "fedora",
                ]
                test: [
                        "98",
                ]
            fail-fast: false
        steps:
            -   name: Set up QEMU
                uses: docker/setup-qemu-action@v3
                with:
                    platforms: 'linux/arm64'
            -   name: "Checkout Repository"
                uses: actions/checkout@v4
            -   name: "${{ matrix.container }} TEST-${{ matrix.test }}"
                run: docker run --platform linux/arm64 --privileged -v /dev:/dev -v $PWD:/w ghcr.io/dracut-ng/${{ matrix.container }} /w/tools/test-github.sh "TEST-${{ matrix.test }}" ${{ matrix.test }}
